version: '3.4'
services:

  ficlo_api:
    restart: always
    build: .
    container_name: "SampleBlockchainAPI"
    command: gunicorn -b 127.0.0.0:8000 'blockchain_api.app:app'
    volumes:
      - .:/SampleBlockchainAPI
    ports:
      - "8000:8000"